# Generated by Django 5.1.1 on 2025-10-23 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0070_alter_video_thumbnail_alter_video_video_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={},
        ),
    ]
