# Generated by Django 5.1.1 on 2025-10-23 19:22

import django.core.validators
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0054_remove_profile_ratings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.FileField(
                blank=True,
                default="profiles/pfps/default.png",
                help_text="(must be a png or jpg between 1kb and 5mb)",
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profilecustomisation",
            name="banner_image",
            field=models.FileField(
                blank=True,
                upload_to="",
                validators=[
                    profiles.models.validate_filesize,
                    profiles.models.validate_image,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profilecustomisation",
            name="video_banner",
            field=models.FileField(
                blank=True,
                upload_to="",
                validators=[
                    profiles.models.validate_filesize,
                    profiles.models.validate_image,
                ],
            ),
        ),
    ]
