# Generated by Django 5.1.1 on 2025-11-28 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0055_alter_profile_followers_and_more"),
        ("videos", "0071_alter_comment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="nominated_video",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="videos.video",
            ),
        ),
    ]
