# Generated by Django 5.1.1 on 2025-11-30 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0056_profile_nominated_video"),
        ("videos", "0072_video_nominations"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="nominated_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.profile",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nominated_video",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="videos.video",
            ),
        ),
    ]
