# Generated by Django 5.1.1 on 2025-11-29 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0022_alter_basenotification_options_and_more"),
        ("profiles", "0056_profile_nominated_video"),
        ("videos", "0072_video_nominations"),
    ]

    operations = [
        migrations.AddField(
            model_name="miscellaneousnotification",
            name="comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_comment",
                to="videos.comment",
            ),
        ),
        migrations.AddField(
            model_name="miscellaneousnotification",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_profile",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="miscellaneousnotification",
            name="video",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_video",
                to="videos.video",
            ),
        ),
    ]
