# Generated by Django 5.1.1 on 2025-11-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0023_miscellaneousnotification_comment_and_more"),
        ("profiles", "0056_profile_nominated_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="miscellaneousnotification",
            name="profiles_to_notify",
            field=models.ManyToManyField(
                blank=True, related_name="profiles_to_notify", to="profiles.profile"
            ),
        ),
    ]
