# Generated by Django 5.1.1 on 2025-11-29 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0024_miscellaneousnotification_profiles_to_notify"),
        ("profiles", "0056_profile_nominated_video"),
        ("videos", "0072_video_nominations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="miscellaneousnotification",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_comment",
                to="videos.comment",
            ),
        ),
        migrations.AlterField(
            model_name="miscellaneousnotification",
            name="message",
            field=models.CharField(
                blank=True,
                default="hi i'm a placeholder nice to meet you",
                max_length=75,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="miscellaneousnotification",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_profile",
                to="profiles.profile",
            ),
        ),
        migrations.AlterField(
            model_name="miscellaneousnotification",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_video",
                to="videos.video",
            ),
        ),
    ]
