# Generated by Django 5.1.1 on 2025-11-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0026_alter_miscellaneousnotification_notified_profiles"),
        ("profiles", "0058_profile_noms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="miscellaneousnotification",
            name="notified_profiles",
            field=models.ManyToManyField(
                blank=True,
                through="notifications.BaseNotification",
                to="profiles.profile",
            ),
        ),
    ]
