# Generated by Django 5.1.1 on 2025-11-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0027_alter_miscellaneousnotification_notified_profiles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="miscellaneousnotification",
            name="profiles_to_notify",
        ),
    ]
